### ISSUE TITLE
Keil microvision 5.32 does not load all my Device components

### ISSUE THREAD

**Issue by fred-r** [MDK-Packs/CB_Lab4Layer#4]
Hi,

I am experimenting the layers with my own packs.
Basically, I took the pack “Keil.STM32L5xx_DFP.1.2.0.pack” and split it into 2 packs:
•	“STMicroelectronics.STM32L5xx_DFP.0.0.2.pack” : only the STM32L5 devices definitions
•	“STMicroelectronics.STM32L5xx_Drivers.0.0.1.pack”: only the HAL and LL drivers

I have installed my 2 packs successfully and created the .clayer enclosed.
I generate a .cprj successfully (enclosed). 

This cpr contains the components I need from my drivers pack:
  <components>
    <component Cclass="CMSIS" Cgroup="CORE" Cvendor="ARM" layer="Board"/>
    <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="CRC" Cvendor="STMicroelectronics"/>
    <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="Common" Cvendor="STMicroelectronics"/>
    <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="Cortex" Cvendor="STMicroelectronics"/>
    <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="RCC" Cvendor="STMicroelectronics"/>
    <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="PWR" Cvendor="STMicroelectronics"/>
    <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="Flash" Cvendor="STMicroelectronics"/>
    <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="EXTI" Cvendor="STMicroelectronics"/>
    <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="GPIO" Cvendor="STMicroelectronics"/>
  </components>

But when I open this cpr with Keil microvision 5.32, I get only the last component, the uvprojx is like this:
    <components>
      <component Cclass="CMSIS" Cgroup="CORE" Cvendor="ARM" Cversion="5.4.0" condition="ARMv6_7_8-M Device" layer="Board">
        <package name="CMSIS" schemaVersion="1.3" url="http://www.keil.com/pack/" vendor="ARM" version="5.7.0"/>
        <targetInfos>
          <targetInfo name="Target 1"/>
        </targetInfos>
      </component>
      <component Cclass="Device" Cgroup="STM32Cube HAL" Csub="GPIO" Cvendor="STMicroelectronics" Cversion="0.0.1" condition="STM32L5 HAL">
        <package name="STM32L5xx_Drivers" schemaVersion="1.6.0" url="" vendor="STMicroelectronics" version="0.0.1"/>
        <targetInfos>
          <targetInfo name="Target 1"/>
        </targetInfos>
      </component>
    </components>

My clayer was working fine with Keil microvision 5.30 (provided that I uninstalled the Keil DFP pack otherwise I was facing the same issue).

Do you have some hints about this behavior ?

Thanks & regards,
Fred
[KeilIssue.zip](https://github.com/MDK-Packs/CB_Lab4Layer/files/5500037/KeilIssue.zip)

**Comment by ReinhardKeil** [comment]
Hi Fred, sorry I cannot duplicate your issue.  Here is what I tried:
- Installed your packs
- Renamed the *.pdsc of the Keil STM32L5 pack so that no device duplication is there
- Opened the *.cprj file

The import then just worked fine.  See the attached file.

I assume your steps are slightly different.

Reinhard

[CRC_userDefinedPolynomial.zip](https://github.com/MDK-Packs/CB_Lab4Layer/files/5500207/CRC_userDefinedPolynomial.zip)

**Comment by fred-r** [comment]
Hi Reinhard,

thanks for your feedback.
I will cross-check my packs repository and see if I can find something.
I'll keep you posted.

Thanks & Regards,
Fred

**Comment by fred-r** [comment]
Hi Reinhard,

I made a big clean-up of my packs repository (I had several versions of my pack and some other vendor names with the same content) and now this is working fine.
It is a bit unclear to me the rationale behind this change, I would have expected the vendor name being a discriminant to avoid mixing-up things.

Sorry for wasting your time and thanks again for your message.
I guess we can close this ticket.

Thanks & Regards,
Fred
