### ISSUE TITLE
question : how to modify the GCC tools ?

### ISSUE THREAD

**Issue by fred-r** [MDK-Packs/CB_Lab4Layer#7]
Hi,

I can see in GCC.9.2.1.mak the following tools definitions:

############ DO NOT EDIT BELOW ###########
AS:=$(TOOLCHAIN_ROOT)/$(PREFIX)as
CC:=$(TOOLCHAIN_ROOT)/$(PREFIX)gcc
CXX:=$(TOOLCHAIN_ROOT)/$(PREFIX)g++
LD:=$(TOOLCHAIN_ROOT)/$(PREFIX)gcc
AR:=$(TOOLCHAIN_ROOT)/$(PREFIX)ar
OC:=$(TOOLCHAIN_ROOT)/$(PREFIX)objcopy

For assembler, the tool to be used is arm-none-eabi-as.
What if I want to use arm-none-eabi-gcc even for assembler files so that I can use more features and directives like "-x assembler-with-cpp" ?

Thanks & Regards,
Fred

**Comment by brondani** [comment]
Hi Fred,

If you want to customize the configuration file (GCC.9.2.1.mak in this case) without touching the original files, just copy it into the project directory and then apply any change that you may be interested, for example changing 'as' by 'gcc'.
Toolchain configuration files in the project directory have precedence over files in the $CMSIS_COMPILER_ROOT directory.

Best regards
Daniel

**Comment by fred-r** [comment]
Hi daniel,

thanks for the explanation, I think we can close this ticket.

Thanks & Regards,
Fred
